### ISSUE TITLE
z-ordering of clones for png

### ISSUE THREAD

**Issue by christopherreay** [ndebeiss/svg3d#4]
Hi, Nicolas,

I dont understand why it should make difference. The svg contains a fixed size png, but the ordering collapses, as in:

![screenshot from 2017-10-03 13-45-24](https://user-images.githubusercontent.com/239550/31148273-21313df2-a841-11e7-8faf-edcdda91b09e.png)

( I know the pictures arent in there, but it actualy makes it much easier to see the ordering reality.

**Comment by ndebeiss** [comment]
Can you try with commit : https://github.com/ndebeiss/svg3d/commit/cedd869b462b8898b0d0f091ec8dba0636fdd5d9
?
I think your images are inside a &lt;g&gt; tag
